version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    container_name: nginx
    depends_on:
      - web
    networks:
      - outside
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
        WORKDIR: /usr/src/light-town-web-app
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      API_URL: ${API_URL}
      API_URL_BROWSER: ${API_URL_BROWSER}
    volumes:
      - .:/usr/src/light-town-web-app
      - node_modules:/usr/src/light-town-web-app/node_modules
    restart: always
    container_name: light-town-web-app
    networks:
      - outside

volumes:
  node_modules:

networks:
  outside:
    driver: bridge
    name: outside