export const GET_ACCOUNT_KEY_SETS = 'GET_ACCOUNT_KEY_SETS';
export const GET_ACCOUNT_KEY_SET = 'GET_ACCOUNT_KEY_SET';

export const GET_TEAM_KEY_SETS = 'GET_TEAM_KEY_SETS';
export const GET_TEAM_KEY_SET = 'GET_TEAM_KEY_SET';

export const SET_MASTER_UNLOCK_KEY = 'SET_MASTER_UNLOCK_KEY';
