export const CREATE_VAULT_FOLDER = 'CREATE_VAULT_FOLDER';
export const SET_CURRENT_VAULT_FOLDER = 'SET_CURRENT_VAULT_FOLDER';
export const GET_NESTED_VAULT_FOLDERS = 'GET_NESTED_VAULT_FOLDERS';
export const GET_ROOT_VAULT_FOLDERS = 'GET_ROOT_VAULT_FOLDERS';
export const CLEAR_VAULT_FOLDER_LIST = 'CLEAR_VAULT_FOLDER_LIST';
export const SET_EXPANDED_VAULT_FOLDER = 'SET_EXPANDED_VAULT_FOLDER';
export const GET_VAULT_FOLDER = 'GET_VAULT_FOLDER';
