export const SET_VAULT_FOLDER = 'SET_VAULT_FOLDER';
export const SET_CURRENT_VAULT_FOLDER_UUID = 'SET_CURRENT_VAULT_FOLDER_UUID';
export const SET_EXPANDED_VAULT_FOLDER = 'SET_EXPANDED_VAULT_FOLDER';
export const CLEAR_VAULT_FOLDER_LIST = 'CLEAR_VAULT_FOLDER_LIST';
export const INCREASE_CONTAINED_VAULT_FOLDER_COUNT =
  'INCREASE_CONTAINED_VAULT_FOLDER_COUNT';
