export const CREATE_ACCOUNT_VAULT = 'CREATE_ACCOUNT_VAULT';

export const GET_ACCOUNT_VAULT = 'GET_ACCOUNT_VAULT';
export const GET_ACCOUNT_VAULTS = 'GET_ACCOUNT_VAULTS';

export const CREATE_TEAM_VAULT = 'CREATE_TEAM_VAULT';

export const GET_TEAM_VAULT = 'GET_TEAM_VAULT';
export const GET_TEAM_VAULTS = 'GET_TEAM_VAULTS';

export const SET_CURRENT_VAULT = 'SET_CURRENT_VAULT';
