export const INIT = 'INIT';

export const GET_VAULT_ITEMS = 'GET_VAULT_ITEMS';
export const GET_VAULT_ITEM = 'GET_VAULT_ITEM';
export const CREATE_VAULT_ITEM = 'CREATE_VAULT_ITEM';
export const SET_CURRENT_VAULT_ITEM = 'SET_CURRENT_VAULT_ITEM';
